function VLMReport({ data }) {
  if (!data) return <div className="detail-panel"><p>No VLM data available.</p></div>

  const explanation = data.vlm_explanation || ''
  const status = data.vlm_status || 'unknown'

  // Simple markdown-to-JSX: headers, bold, lists
  const renderMarkdown = (text) => {
    const lines = text.split('\n')
    const elements = []
    let listItems = []

    const flushList = () => {
      if (listItems.length > 0) {
        elements.push(
          <ul key={`ul-${elements.length}`} className="vlm-list">
            {listItems.map((li, i) => <li key={i}>{renderInline(li)}</li>)}
          </ul>
        )
        listItems = []
      }
    }

    const renderInline = (line) => {
      // Bold **text**
      const parts = []
      let remaining = line
      let key = 0
      while (remaining) {
        const boldMatch = remaining.match(/\*\*(.+?)\*\*/)
        if (boldMatch) {
          const idx = remaining.indexOf(boldMatch[0])
          if (idx > 0) parts.push(<span key={key++}>{remaining.slice(0, idx)}</span>)
          parts.push(<strong key={key++}>{boldMatch[1]}</strong>)
          remaining = remaining.slice(idx + boldMatch[0].length)
        } else {
          parts.push(<span key={key++}>{remaining}</span>)
          remaining = ''
        }
      }
      return parts
    }

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]

      // Headers
      if (line.startsWith('### ')) {
        flushList()
        elements.push(<h5 key={i} className="vlm-h3">{renderInline(line.slice(4))}</h5>)
      } else if (line.startsWith('## ')) {
        flushList()
        elements.push(<h4 key={i} className="vlm-h2">{renderInline(line.slice(3))}</h4>)
      } else if (line.startsWith('# ')) {
        flushList()
        elements.push(<h3 key={i} className="vlm-h1">{renderInline(line.slice(2))}</h3>)
      }
      // List items
      else if (line.match(/^[-*]\s/)) {
        listItems.push(line.replace(/^[-*]\s/, ''))
      }
      else if (line.match(/^\d+\.\s/)) {
        listItems.push(line.replace(/^\d+\.\s/, ''))
      }
      // Empty line
      else if (line.trim() === '') {
        flushList()
      }
      // Paragraph
      else {
        flushList()
        elements.push(<p key={i} className="vlm-paragraph">{renderInline(line)}</p>)
      }
    }
    flushList()
    return elements
  }

  return (
    <div className="detail-panel">
      <h3>AI Explanation (Gemini VLM)</h3>

      {status === 'error' && (
        <div className="vlm-status-badge vlm-error">VLM service encountered an error</div>
      )}
      {status === 'success' && (
        <div className="vlm-status-badge vlm-success">Generated by Gemini 2.0 Flash</div>
      )}

      <div className="vlm-content">
        {renderMarkdown(explanation)}
      </div>

      <div className="vlm-disclaimer">
        This explanation was generated by an AI language model and is intended for educational and research purposes only.
        It should not be used as a substitute for professional medical advice, diagnosis, or treatment.
      </div>
    </div>
  )
}

export default VLMReport
